spring.application.name=reserva

# Configuracion de BDD
spring.datasource.url=jdbc:mysql://localhost:3306/h_reserva
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto de la API
server.port=8081

# Seguridad OAuth2 Resource Server (JWT de Azure Entra ID)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/TENANT_ID/v2.0
