spring.application.name=RabbitMQ

server.port=8080

#Config rabbitMQ:
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.rabbitmq.virtual-host=/

#Config de listeners
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=5

#Config de Logging
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework.amqp=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} -%msg%n