spring.application.name=usuario

# Configuracion de BDD
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:h_usuario}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto de la API
server.port=${SERVER_PORT:8083}

# Seguridad OAuth2 Resource Server (JWT de Azure Entra ID)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID:e34a6311-e69d-4a97-bedf-2ad7cc5455a0}/v2.0
