spring.application.name=servicio

# Configuracion de BDD
spring.datasource.url=jdbc:mysql://localhost:3306/h_servicio
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto de la API
server.port=8082

# Configurar Microsoft Entra ID

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id="0dffbac7-2223-48cb-85c8-ba2376e4e633"
spring.cloud.azure.active-directory.app-id-url="http://localhost:8082"